# stage 1: install dependencies
FROM python:3.12-slim AS builder

WORKDIR /backend

USER root

RUN apt-get update && apt-get install -y \
  build-essential \
  libpq-dev \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip
RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

# stage 2: run
FROM python:3.12-slim

WORKDIR /backend

USER root

RUN apt-get update && apt-get install -y \
  curl \
  && rm -rf /var/lib/apt/lists/*

COPY --from=builder /install /usr/local
COPY . .

CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:1234", "Application:create_app()"]